### ISSUE TITLE
Utilizar o Docker Compose para gerenciar os múltiplos containers

### ISSUE THREAD

**Issue by clelsonsalles** [culturagovbr/docker-GOG#1]
Os dois containers projetados (postgre9.3 e gog) estão funcionando com a opção "--link", da linha de comando do Docker.
Precisamos evoluir a integração dos containers para utilizar a solução "Docker Compose"

**Comment by gomex** [comment]
Ta aqui o PR: https://github.com/culturagovbr/docker-GOG/pull/2

**Comment by gomex** [comment]
Isso aqui já ta concluído né @nitaibezerra @clelsonsalles ?

**Comment by clelsonsalles** [comment]
Marcando o issue como concluído.
Acrescentamos no projeto a utilização do Docker compose
