### ISSUE TITLE
Utilizar OpenJDK no lugar do JDK da Oracle

### ISSUE THREAD

**Issue by nitaibezerra** [culturagovbr/docker-GOG#3]
Sugestão do @gomex. Alguns questionamentos estão surgindo quando ao infrigimento de licença ao disponibilizar uma imagem com o JDK da Oracle.

**Comment by gomex** [comment]
Olha o link: http://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/

**Comment by chris-redfield** [comment]
eita ://

**Comment by gomex** [comment]
Se mudarmos a forma como é construindo o ambiente hoje, ou seja, usar a imagem base java, podemos testar isso em segundos. Será meu próximo PR :P

**Comment by gomex** [comment]
PR feito: https://github.com/culturagovbr/docker-GOG/pull/4

**Comment by gomex** [comment]
Isso aqui já ta concluído né @nitaibezerra @clelsonsalles ?

**Comment by clelsonsalles** [comment]
Marcando o issue como concluído.
No Dockerfile utilizamos o "openjdk" do repositório docker como imagem principal > "FROM java:openjdk-7-jdk"

**Comment by clelsonsalles** [comment]
Marcando o issue como concluído.
No Dockerfile utilizamos o "openjdk" do repositório docker como imagem principal > "FROM java:openjdk-7-jdk"
